version: '3.8'

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /Users/aymerikikette/42/easy_inception/data/wordpress

  db:
    name: db
    driver_opts:
      type: none
      o: bind
      device: /Users/aymerikikette/42/easy_inception/data/db

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - network
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - network
    volumes:
      - wordpress:/var/www/wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MARIADB_HOST=${MARIADB_HOST}
      - WP_ADMIN_USR=${WP_ADMIN_USR}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USR=${WP_USR}
      - WP_PWD=${WP_PWD}
      - WP_EMAIL=${WP_EMAIL}
      - WP_DB_NAME=${WP_DB_NAME}
      - WP_DB_USR=$WP_DB_USR
      - WP_DB_PWD=$WP_DB_PWD
      - WP_TITLE=$WP_TITLE
    stdin_open: true #tmp
    tty: true #tmp

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - network
    volumes:
      - db:/val/lib/mysql
    environment:
      - WP_DB_NAME=$WP_DB_NAME
      - WP_DB_USR=$WP_DB_USR
      - WP_DB_PWD=$WP_DB_PWD
      - MARIADB_ROOT_PWD=$MARIADB_ROOT_PWD
    stdin_open: true #tmp
    tty: true #tmp

networks:
  network:
    name: network
