version: "3"

volumes:
  wp_site:
    name: wp_site
    driver_opts:
      type: none
      o: bind
      device: /home/amuhleth/data/wp_site
  wp_db:
    name: wp_db
    driver_opts:
      type: none
      o: bind
      device: /home/amuhleth/data/wp_db

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_site:/var/www/wordpress
    restart:  unless-stopped
    networks:
      - network
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wp_site:/var/www/wordpress
    env_file:
      - .env
    restart:  unless-stopped
    networks:
      - network
    depends_on:
      - mariadb

  mariadb:
    build:
      context: requirements/mariadb
    container_name: mariadb
    volumes:
      - wp_db:/var/lib/mysql
    env_file:
      - .env
    restart:  unless-stopped
    networks:
      - network

networks:
  network:
